import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const onest = localFont({
  src: [
    {
      path: '../../public/fonts/onest/Onest-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/onest/Onest-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/onest/Onest-medium.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-onest',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} bg-light-blue antialiased`}>
        {children}
      </body>
    </html>
  );
}
