import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const montserrat = localFont({
  src: [
    {
      path: '../../public/fonts/montserrat-alternates/MontserratAlternates-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/montserrat-alternates/MontserratAlternates-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/montserrat-alternates/MontserratAlternates-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-montserrat-alternates',
});

const onest = localFont({
  src: [
    {
      path: '../../public/fonts/onest/Onest-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-onest',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${onest.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
